enum Actions {
  SET_CURRENT_REQUEST_LISTS,
  SET_REQUEST_LISTS_ON_CONSULTING_TOGGLE,

  ADD_FILTERING_METHOD_LIST,
  SUB_FILTERING_METHOD_LIST,

  ADD_FILTERING_MATERIAL_LIST,
  SUB_FILTERING_MATERIAL_LIST,

  RESET_FILTERING_OPTIONS,

  TOGGLE_NAVBAR_MENU,
  RESET_NAVBAR_MENU,
}

export default Actions;
